// ====== DATA DUMMY TUGAS PER DINAS ======
export const DUMMY_TUGAS = {
    'Dinas Pekerjaan Umum': [
        { id: 'LPW-2024-001284', judul: 'Jalan Rusak di Jl. Solo', kategori: 'Infrastruktur', lokasi: 'Kec. Umbulharjo', tanggal: '2024-12-08', prioritas: 'Tinggi', status: 'Menunggu', pelapor: 'Budi Santoso', deskripsi: 'Jalan berlubang besar di Jl. Solo KM 5 sepanjang 50 meter, membahayakan pengendara motor terutama saat malam hari.' },
        { id: 'LPW-2024-001280', judul: 'Trotoar Ambles di Jl. Malioboro', kategori: 'Infrastruktur', lokasi: 'Kec. Gedongtengen', tanggal: '2024-12-06', prioritas: 'Tinggi', status: 'Diproses', pelapor: 'Sari Dewi', deskripsi: 'Trotoar di depan Toko ABC ambles sedalam 30cm, pejalan kaki terpaksa berjalan di badan jalan.' },
        { id: 'LPW-2024-001275', judul: 'Drainase Tersumbat di Gang Mangga', kategori: 'Infrastruktur', lokasi: 'Kec. Mergangsan', tanggal: '2024-12-03', prioritas: 'Sedang', status: 'Diproses', pelapor: 'Anonim', deskripsi: 'Saluran drainase tersumbat sampah sehingga air meluap saat hujan dan menggenangi jalan setinggi 20cm.' },
        { id: 'LPW-2024-001270', judul: 'Jembatan Retak di Sungai Code', kategori: 'Infrastruktur', lokasi: 'Kec. Jetis', tanggal: '2024-11-28', prioritas: 'Tinggi', status: 'Selesai', pelapor: 'Hendra Wijaya', deskripsi: 'Retakan besar di jembatan penyeberangan Sungai Code, sudah ditandai dengan cat merah oleh warga.' },
        { id: 'LPW-2024-001265', judul: 'Aspal Mengelupas di Jl. Kaliurang', kategori: 'Infrastruktur', lokasi: 'Kec. Gondokusuman', tanggal: '2024-11-25', prioritas: 'Sedang', status: 'Selesai', pelapor: 'Yuni Astuti', deskripsi: 'Aspal mengelupas sepanjang 100m di Jl. Kaliurang KM 7, sudah beberapa kali ditambal tapi rusak lagi.' },
        { id: 'LPW-2024-001260', judul: 'PJU Mati di Jl. Godean', kategori: 'Infrastruktur', lokasi: 'Kec. Gamping', tanggal: '2024-11-20', prioritas: 'Rendah', status: 'Selesai', pelapor: 'Bambang S.', deskripsi: '5 tiang PJU berturut-turut mati di Jl. Godean KM 3, area menjadi sangat gelap di malam hari.' },
        { id: 'LPW-2024-001255', judul: 'Gorong-gorong Rusak Jl. Bantul', kategori: 'Infrastruktur', lokasi: 'Kec. Mantrijeron', tanggal: '2024-11-15', prioritas: 'Sedang', status: 'Menunggu', pelapor: 'Rini Kusuma', deskripsi: 'Gorong-gorong di bawah jalan pecah sehingga air mengalir ke jalan dan merusak aspal di sekitarnya.' },
        { id: 'LPW-2024-001250', judul: 'Tembok Penahan Longsor', kategori: 'Infrastruktur', lokasi: 'Kec. Kotagede', tanggal: '2024-11-10', prioritas: 'Tinggi', status: 'Diproses', pelapor: 'Eko Prasetyo', deskripsi: 'Tembok penahan tanah di tepi sungai retak dan miring, berpotensi longsor saat musim hujan.' },
        { id: 'LPW-2024-001245', judul: 'Paving Block Rusak di Taman Kota', kategori: 'Infrastruktur', lokasi: 'Kec. Danurejan', tanggal: '2024-10-30', prioritas: 'Rendah', status: 'Selesai', pelapor: 'Lisa Marlina', deskripsi: 'Paving block di area taman kota banyak yang patah and tidak rata, berbahaya untuk anak-anak bermain.' },
        { id: 'LPW-2024-001240', judul: 'Saluran Irigasi Bocor', kategori: 'Infrastruktur', lokasi: 'Kec. Tegalrejo', tanggal: '2024-10-25', prioritas: 'Sedang', status: 'Menunggu', pelapor: 'Pak Sutarno', deskripsi: 'Saluran irigasi utama bocor di 3 titik, air terbuang sia-sia dan sawah di hilir kekurangan air.' },
    ],
    'BPBD': [
        { id: 'LPW-2024-001277', judul: 'Banjir di Gang Mawar', kategori: 'Bencana', lokasi: 'Kec. Umbulharjo', tanggal: '2024-12-05', prioritas: 'Tinggi', status: 'Diproses', pelapor: 'Anonim', deskripsi: 'Banjir setinggi 50cm merendam 15 rumah warga di Gang Mawar RT 05, evakuasi diperlukan.' },
        { id: 'LPW-2024-001273', judul: 'Pohon Tumbang di Jl. Parangtritis', kategori: 'Bencana', lokasi: 'Kec. Kretek', tanggal: '2024-12-02', prioritas: 'Tinggi', status: 'Selesai', pelapor: 'Agus Setiawan', deskripsi: 'Pohon besar tumbang menutup jalan utama akibat angin kencang, lalu lintas total terhambat.' },
        { id: 'LPW-2024-001268', judul: 'Tanah Longsor di Bukit Bintang', kategori: 'Bencana', lokasi: 'Kec. Piyungan', tanggal: '2024-11-27', prioritas: 'Tinggi', status: 'Menunggu', pelapor: 'Warga RT 03', deskripsi: 'Longsoran tanah menutupi akses jalan ke 8 rumah warga, material tanah sekitar 200m³.' },
        { id: 'LPW-2024-001262', judul: 'Kebakaran Lahan Kosong', kategori: 'Bencana', lokasi: 'Kec. Depok', tanggal: '2024-11-22', prioritas: 'Sedang', status: 'Selesai', pelapor: 'Dedi Kurniawan', deskripsi: 'Lahan kosong seluas 1 hektar terbakar, api berpotensi menjalar ke pemukiman warga di sekitarnya.' },
        { id: 'LPW-2024-001257', judul: 'Genangan Air Berkepanjangan', kategori: 'Bencana', lokasi: 'Kec. Gondokusuman', tanggal: '2024-11-18', prioritas: 'Sedang', status: 'Diproses', pelapor: 'Ibu Maryam', deskripsi: 'Genangan air tidak surut selama 3 hari di kompleks perumahan, diduga saluran pembuangan tersumbat.' },
        { id: 'LPW-2024-001252', judul: 'Retakan Tanah di Area Pemukiman', kategori: 'Bencana', lokasi: 'Kec. Ngemplak', tanggal: '2024-11-12', prioritas: 'Tinggi', status: 'Menunggu', pelapor: 'Pak Jumadi', deskripsi: 'Retakan tanah sepanjang 30m ditemukan di belakang 5 rumah warga, lebar retakan 10-15cm.' },
        { id: 'LPW-2024-001247', judul: 'Angin Puting Beliung', kategori: 'Bencana', lokasi: 'Kec. Mlati', tanggal: '2024-11-05', prioritas: 'Tinggi', status: 'Selesai', pelapor: 'Kepala Dusun', deskripsi: 'Angin puting beliung merusak atap 20 rumah dan menumbangkan 8 pohon besar di area permukiman.' },
    ],
    'Dinas Lingkungan Hidup': [
        { id: 'LPW-2024-001282', judul: 'Tumpukan Sampah Liar di Jl. Wonosari', kategori: 'Lingkungan', lokasi: 'Kec. Banguntapan', tanggal: '2024-12-07', prioritas: 'Sedang', status: 'Menunggu', pelapor: 'Ani Suryani', deskripsi: 'Tumpukan sampah liar di pinggir jalan sudah menggunung, menimbulkan bau tidak sedap dan lalat.' },
        { id: 'LPW-2024-001278', judul: 'Limbah Pabrik Mencemari Sungai', kategori: 'Lingkungan', lokasi: 'Kec. Sewon', tanggal: '2024-12-05', prioritas: 'Tinggi', status: 'Diproses', pelapor: 'Forum Warga Peduli Lingkungan', deskripsi: 'Air sungai berubah warna hitam dan berbau kimia, ikan-ikan mati, diduga limbah dari pabrik tekstil.' },
        { id: 'LPW-2024-001274', judul: 'Polusi Udara dari Pembakaran', kategori: 'Lingkungan', lokasi: 'Kec. Kasihan', tanggal: '2024-12-03', prioritas: 'Sedang', status: 'Selesai', pelapor: 'Dr. Ratna', deskripsi: 'Pembakaran sampah plastik setiap malam di area TPA ilegal, asap tebal mengganggu 3 RT sekitar.' },
        { id: 'LPW-2024-001269', judul: 'Pohon Tua Berpotensi Tumbang', kategori: 'Lingkungan', lokasi: 'Kec. Gondokusuman', tanggal: '2024-11-28', prioritas: 'Sedang', status: 'Menunggu', pelapor: 'Pak Suryo', deskripsi: 'Pohon beringin besar di halaman sekolah condong 45 derajat, akar sudah terangkat sebagian.' },
        { id: 'LPW-2024-001264', judul: 'Sampah di Bantaran Sungai Code', kategori: 'Lingkungan', lokasi: 'Kec. Mergangsan', tanggal: '2024-11-24', prioritas: 'Tinggi', status: 'Diproses', pelapor: 'Komunitas Peduli Sungai', deskripsi: 'Sampah plastik dan rumah tangga menumpuk di bantaran sungai sepanjang 500m, menyumbat aliran air.' },
        { id: 'LPW-2024-001259', judul: 'Pencemaran Sumur Warga', kategori: 'Lingkungan', lokasi: 'Kec. Kotagede', tanggal: '2024-11-19', prioritas: 'Tinggi', status: 'Selesai', pelapor: 'Ibu Wati', deskripsi: 'Air sumur berubah keruh dan berbau, 12 KK terdampak, diduga tercemar limbah bengkel di dekatnya.' },
        { id: 'LPW-2024-001254', judul: 'TPA Ilegal di Lahan Kosong', kategori: 'Lingkungan', lokasi: 'Kec. Depok', tanggal: '2024-11-14', prioritas: 'Sedang', status: 'Menunggu', pelapor: 'Anonim', deskripsi: 'Lahan kosong dijadikan TPA ilegal oleh oknum, volume sampah terus bertambah setiap hari.' },
        { id: 'LPW-2024-001249', judul: 'Kebisingan Pabrik di Malam Hari', kategori: 'Lingkungan', lokasi: 'Kec. Gamping', tanggal: '2024-11-08', prioritas: 'Rendah', status: 'Selesai', pelapor: 'Warga RT 08', deskripsi: 'Pabrik beroperasi 24 jam dengan kebisingan melebihi batas wajar, warga sekitar sulit tidur.' },
    ],
};

// Default kosong jika dinas tidak ditemukan
export const getTasksForDinas = (dinas) => DUMMY_TUGAS[dinas] || [];
